services:
  # Backend Flask
  - type: web
    name: tradingroad-backend
    runtime: python
    region: frankfurt
    plan: Starter
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "cd tradingroad_py && gunicorn --config ../gunicorn.conf.py app:app"
    healthCheckPath: "/dashboard"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        generateValue: true
      - key: FLASK_ENV
        value: "production"
      - key: DEBUG
        value: "false"
      - key: FRONTEND_URL
        value: "https://tradingroad-frontend.onrender.com"
      # Optimización de memoria
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      # Variables de API - agregar desde el dashboard de Render
      - key: GEMINI_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
    autoDeploy: true

  # Frontend React
  - type: web
    name: tradingroad-frontend
    runtime: node
    region: frankfurt
    plan: Starter
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    envVars:
      - key: VITE_BACKEND_URL
        value: "https://tradingroad-backend.onrender.com"
      # Variables de API para el frontend
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: VITE_FINNHUB_API_KEY
        sync: false
      - key: VITE_FMP_API_KEY
        sync: false
    autoDeploy: true
