services:
  - type: web
    name: tradingroad-platform
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: python run.py
    healthCheckPath: /dashboard
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
    autoDeploy: true
