services:
  - type: web
    name: tradingroad-platform
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd tradingroad_py && 
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: cd tradingroad_py && python app.py --port $PORT
    healthCheckPath: /dashboard
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: PORT
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
    autoDeploy: true
